### PR TITLE
few tweaks to improve selection with vim visual modes

### PR DESCRIPTION
**Pull request by andrewplummer**
This attempts to address issues when trying to select while in visualLine mode in the vim extension to match vim behavior

- cancel current selection and try to check if visual line mode is active
- more accurate selection of characters around cursor (don't select entire line unless visualLine is active)

### CODE REVIEW

**Comment by redguardtoo** [comment]
Why there are two `setTimeout`?  Please clean code a bit.

The timeout time had better be 200 milliseconds. People might use vscode on slower machine.

**Comment by andrewplummer** [comment]
The second one is similar to the first, to allow the command `vscode.commands.executeCommand('cancelSelection');` to clear. Yes 200ms is fine, although how do we arrive at a reasonable value for this? What if it's slower than 200ms?

**Comment by redguardtoo** [comment]
> The second one is similar to the first, to allow the command `vscode.commands.executeCommand('cancelSelection');` to clear. Yes 200ms is fine, although how do we arrive at a reasonable value for this? What if it's slower than 200ms?

Second timeout looks fine. Could set the both timeout to 150, squash the commit, and force push?

I

**Comment by andrewplummer** [comment]
done

**Comment by redguardtoo** [comment]
Thanks

**Comment by andrewplummer** [comment]
Thank you for a very useful extension!

**Pull request merged**
